name: synthguard_crisis_tracker
description: Tracking Crisis Events on Base Sepolia

networks:
  - id: 84532
    start_block: 34900000
    rpc_config:
      url: https://sepolia.base.org
    

    contracts:
      - name: MockLending
        address: 0x76Bb074046e707481D6ba9cc7301e39912dC0EE1
        handler: src/EventHandlers.js
        abi_file_path: abis/MockLending.json
        events:
          - event: "HealthFactorUpdated(address indexed user, uint256 newHealth)"
          - event: "RescueExecuted(address indexed user, uint256 debtRepaid)"
      
     

      - name: GuardianManager
        address: 0xDA0dFcC5A305F10EBfb0791A8Ce59Ca8FB2F0C92             
        handler: src/EventHandlers.js
        events:
          - event: FundsDelegated(address indexed user, address indexed workerAgent, uint256 amount)
          - event: AgentStatusUpdated(address indexed agent, bool isActive)