# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: synthguard-indexer
networks:
- id: 1
  start_block: 0
  contracts:
  - name: USDT
    address:
    - 0xdAC17F958D2ee523a2206206994597C13D831ec7
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
    - event: Transfer(address indexed from, address indexed to, uint256 value)
unordered_multichain_mode: true
preload_handlers: true
